# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-26 23:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artistprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('release_title', models.CharField(max_length=100)),
                ('release_date', models.DateTimeField(auto_now_add=True)),
                ('audio_file_url', models.CharField(max_length=255)),
                ('image_file_url', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='artistprofile.ArtistProfile')),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL))
            ],
        ),
    ]
