CREATE PROCEDURE [dbo].[DeleteAndSeedGenres]
AS
BEGIN
	DELETE FROM [Genre];

	DBCC CHECKIDENT ('[Genre]', RESEED, 0);

	INSERT INTO Genre VALUES (LOWER(REPLACE('Alternative', ' ', '-')), 'Alternative');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Blues', ' ', '-')), 'Blues');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Classical', ' ', '-')), 'Classical');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Comedy', ' ', '-')), 'Comedy');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Country', ' ', '-')), 'Country');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Electronic', ' ', '-')), 'Electronic');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Hip-Hop-Rap', ' ', '-')), 'Hip-Hop/Rap');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Jazz', ' ', '-')), 'Jazz');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Pop', ' ', '-')), 'Pop');
	INSERT INTO Genre VALUES (LOWER(REPLACE('R-B', ' ', '-')), 'R&B');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Reggae', ' ', '-')), 'Reggae');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Punk', ' ', '-')), 'Punk');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Rock', ' ', '-')), 'Rock');
	INSERT INTO Genre VALUES (LOWER(REPLACE('2-Step', ' ', '-')), '2-Step');
	INSERT INTO Genre VALUES (LOWER(REPLACE('2-Tone', ' ', '-')), '2-Tone');
	INSERT INTO Genre VALUES (LOWER(REPLACE('A cappella', ' ', '-')), 'A cappella');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Acid Jazz', ' ', '-')), 'Acid Jazz');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Acid Rock', ' ', '-')), 'Acid Rock');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Acoustic Blues', ' ', '-')), 'Acoustic Blues');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Adult-Oriented Rock', ' ', '-')), 'Adult-Oriented Rock');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Adult Alternative', ' ', '-')), 'Adult Alternative');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Adult Contemporary', ' ', '-')), 'Adult Contemporary');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Africa', ' ', '-')), 'Africa');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Afro-Beat', ' ', '-')), 'Afro-Beat');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Afro-Pop', ' ', '-')), 'Afro-Pop');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Afro Punk', ' ', '-')), 'Afro Punk');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Alternative Country', ' ', '-')), 'Alternative Country');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Alternative Folk', ' ', '-')), 'Alternative Folk');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Alternative Rap', ' ', '-')), 'Alternative Rap');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Alternative Rock', ' ', '-')), 'Alternative Rock');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Alternativo & Rock Latino', ' ', '-')), 'Alternativo & Rock Latino');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Ambient', ' ', '-')), 'Ambient');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Americana', ' ', '-')), 'Americana');
	INSERT INTO Genre VALUES (LOWER(REPLACE('American Trad Rock', ' ', '-')), 'American Trad Rock');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Anatolian Rock', ' ', '-')), 'Anatolian Rock');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Arena Rock', ' ', '-')), 'Arena Rock');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Argentine tango', ' ', '-')), 'Argentine tango');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Art Punk', ' ', '-')), 'Art Punk');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Art Rock', ' ', '-')), 'Art Rock');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Asia', ' ', '-')), 'Asia');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Australia', ' ', '-')), 'Australia');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Avant-Garde', ' ', '-')), 'Avant-Garde');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Avant-Garde Jazz', ' ', '-')), 'Avant-Garde Jazz');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Baladas y Boleros', ' ', '-')), 'Baladas y Boleros');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Barbershop', ' ', '-')), 'Barbershop');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Baroque', ' ', '-')), 'Baroque');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Bebop', ' ', '-')), 'Bebop');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Big Band', ' ', '-')), 'Big Band');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Black Metal', ' ', '-')), 'Black Metal');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Bluegrass', ' ', '-')), 'Bluegrass');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Blue Note', ' ', '-')), 'Blue Note');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Blues-Rock', ' ', '-')), 'Blues-Rock');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Bop', ' ', '-')), 'Bop');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Bossa Nova', ' ', '-')), 'Bossa Nova');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Bounce', ' ', '-')), 'Bounce');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Brazilian', ' ', '-')), 'Brazilian');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Breakbeat Breakstep', ' ', '-')), 'Breakbeat / Breakstep');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Breakcore', ' ', '-')), 'Breakcore');
	INSERT INTO Genre VALUES (LOWER(REPLACE('British Invasion', ' ', '-')), 'British Invasion');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Britpop', ' ', '-')), 'Britpop');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Brostep', ' ', '-')), 'Brostep');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Bubblegum Pop', ' ', '-')), 'Bubblegum Pop');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Cajun', ' ', '-')), 'Cajun');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Calypso', ' ', '-')), 'Calypso');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Caribbean', ' ', '-')), 'Caribbean');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Carnatic', ' ', '-')), 'Carnatic');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Celtic', ' ', '-')), 'Celtic');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Celtic Folk', ' ', '-')), 'Celtic Folk');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Chamber Music', ' ', '-')), 'Chamber Music');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Chamber Pop', ' ', '-')), 'Chamber Pop');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Chant', ' ', '-')), 'Chant');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Chicago Blues', ' ', '-')), 'Chicago Blues');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Chicano', ' ', '-')), 'Chicano');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Chillstep', ' ', '-')), 'Chillstep');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Choral', ' ', '-')), 'Choral');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Christian & Gospel', ' ', '-')), 'Christian & Gospel');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Christian Metal', ' ', '-')), 'Christian Metal');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Christian Pop', ' ', '-')), 'Christian Pop');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Christian Rap', ' ', '-')), 'Christian Rap');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Christian Rock', ' ', '-')), 'Christian Rock');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Club Dance', ' ', '-')), 'Club / Club Dance');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Cock Rock', ' ', '-')), 'Cock Rock');
	INSERT INTO Genre VALUES (LOWER(REPLACE('College Rock', ' ', '-')), 'College Rock');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Commercial', ' ', '-')), 'Commercial');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Conjunto', ' ', '-')), 'Conjunto');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Conjunto Progressive', ' ', '-')), 'Conjunto Progressive');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Contemporary Bluegrass', ' ', '-')), 'Contemporary Bluegrass');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Contemporary Blues', ' ', '-')), 'Contemporary Blues');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Contemporary Celtic', ' ', '-')), 'Contemporary Celtic');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Contemporary Classical', ' ', '-')), 'Contemporary Classical');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Contemporary Country', ' ', '-')), 'Contemporary Country');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Contemporary Folk', ' ', '-')), 'Contemporary Folk');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Contemporary Gospel', ' ', '-')), 'Contemporary Gospel');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Contemporary Jazz', ' ', '-')), 'Contemporary Jazz');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Contemporary Latin', ' ', '-')), 'Contemporary Latin');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Contemporary R&B', ' ', '-')), 'Contemporary R&B');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Cool', ' ', '-')), 'Cool');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Country Blues', ' ', '-')), 'Country Blues');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Country Gospel', ' ', '-')), 'Country Gospel');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Country Pop', ' ', '-')), 'Country Pop');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Coupe-decale – Congo', ' ', '-')), 'Coupé-décalé – Congo');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Crossover Jazz', ' ', '-')), 'Crossover Jazz');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Crossover Thrash', ' ', '-')), 'Crossover Thrash');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Crunk', ' ', '-')), 'Crunk');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Crust Punk', ' ', '-')), 'Crust Punk');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Cumbia', ' ', '-')), 'Cumbia');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Dance', ' ', '-')), 'Dance');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Dancehall', ' ', '-')), 'Dancehall');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Dance Pop', ' ', '-')), 'Dance Pop');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Dangdut', ' ', '-')), 'Dangdut');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Death Metal', ' ', '-')), 'Death Metal');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Deep House', ' ', '-')), 'Deep House');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Delta Blues', ' ', '-')), 'Delta Blues');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Dirty South', ' ', '-')), 'Dirty South');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Disco', ' ', '-')), 'Disco');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Dixieland', ' ', '-')), 'Dixieland');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Doom Metal', ' ', '-')), 'Doom Metal');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Doo Wop', ' ', '-')), 'Doo Wop');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Downtempo', ' ', '-')), 'Downtempo');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Dream Pop', ' ', '-')), 'Dream Pop');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Drinking Songs', ' ', '-')), 'Drinking Songs');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Drone', ' ', '-')), 'Drone');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Drum Bass', ' ', '-')), 'Drum & Bass');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Dub', ' ', '-')), 'Dub');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Dubstep', ' ', '-')), 'Dubstep');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Early Music', ' ', '-')), 'Early Music');
	INSERT INTO Genre VALUES (LOWER(REPLACE('East Coast Rap', ' ', '-')), 'East Coast Rap');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Easy Listening', ' ', '-')), 'Easy Listening');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Electric Blues', ' ', '-')), 'Electric Blues');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Electro', ' ', '-')), 'Electro');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Electro-swing', ' ', '-')), 'Electro-swing');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Electro House', ' ', '-')), 'Electro House');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Electronica', ' ', '-')), 'Electronica');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Electronic Rock', ' ', '-')), 'Electronic Rock');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Electro Pop', ' ', '-')), 'Electro Pop');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Electroswing', ' ', '-')), 'Electroswing');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Environmental', ' ', '-')), 'Environmental');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Ethio-jazz', ' ', '-')), 'Ethio-jazz');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Europe', ' ', '-')), 'Europe');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Exercise', ' ', '-')), 'Exercise');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Experimental', ' ', '-')), 'Experimental');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Expressionist', ' ', '-')), 'Expressionist');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Flamenco', ' ', '-')), 'Flamenco');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Folk Rock', ' ', '-')), 'Folk Rock');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Folk Punk', ' ', '-')), 'Folk Punk');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Foreign Cinema', ' ', '-')), 'Foreign Cinema');
	INSERT INTO Genre VALUES (LOWER(REPLACE('France', ' ', '-')), 'France');
	INSERT INTO Genre VALUES (LOWER(REPLACE('French Pop', ' ', '-')), 'French Pop');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Funk', ' ', '-')), 'Funk');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Fusion', ' ', '-')), 'Fusion');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Future Garage', ' ', '-')), 'Future Garage');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Gangsta Rap', ' ', '-')), 'Gangsta Rap');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Garage', ' ', '-')), 'Garage');
	INSERT INTO Genre VALUES (LOWER(REPLACE('German Folk', ' ', '-')), 'German Folk');
	INSERT INTO Genre VALUES (LOWER(REPLACE('German Pop', ' ', '-')), 'German Pop');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Glam Rock', ' ', '-')), 'Glam Rock');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Glitch Hop', ' ', '-')), 'Glitch Hop');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Glitch Pop', ' ', '-')), 'Glitch Pop');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Gospel', ' ', '-')), 'Gospel');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Gothic Rock', ' ', '-')), 'Gothic Rock');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Gothic Metal', ' ', '-')), 'Gothic Metal');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Gregorian Chant', ' ', '-')), 'Gregorian Chant');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Grime', ' ', '-')), 'Grime');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Grind Core', ' ', '-')), 'Grind Core');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Grunge', ' ', '-')), 'Grunge');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Gypsy Jazz', ' ', '-')), 'Gypsy Jazz');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Hair Metal', ' ', '-')), 'Hair Metal');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Hard Bop', ' ', '-')), 'Hard Bop');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Hardcore', ' ', '-')), 'Hardcore');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Hardcore Punk', ' ', '-')), 'Hardcore Punk');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Hardcore Rap', ' ', '-')), 'Hardcore Rap');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Hard Dance', ' ', '-')), 'Hard Dance');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Hard Rock', ' ', '-')), 'Hard Rock');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Hardstyle', ' ', '-')), 'Hardstyle');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Hawaii', ' ', '-')), 'Hawaii');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Healing', ' ', '-')), 'Healing');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Eurodance', ' ', '-')), 'Eurodance');
	INSERT INTO Genre VALUES (LOWER(REPLACE('High Classical', ' ', '-')), 'High Classical');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Hindustani', ' ', '-')), 'Hindustani');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Honky Tonk', ' ', '-')), 'Honky Tonk');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Horrorcore', ' ', '-')), 'Horrorcore');
	INSERT INTO Genre VALUES (LOWER(REPLACE('House', ' ', '-')), 'House');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Impressionist', ' ', '-')), 'Impressionist');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Indian Ghazal', ' ', '-')), 'Indian Ghazal');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Indian Pop', ' ', '-')), 'Indian Pop');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Indie Folk', ' ', '-')), 'Indie Folk');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Indie Pop', ' ', '-')), 'Indie Pop');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Indie Rock', ' ', '-')), 'Indie Rock');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Industrial', ' ', '-')), 'Industrial');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Instrumental', ' ', '-')), 'Instrumental');
	INSERT INTO Genre VALUES (LOWER(REPLACE('J-Pop', ' ', '-')), 'J-Pop');
	INSERT INTO Genre VALUES (LOWER(REPLACE('J-Punk', ' ', '-')), 'J-Punk');
	INSERT INTO Genre VALUES (LOWER(REPLACE('J-Rock', ' ', '-')), 'J-Rock');
	INSERT INTO Genre VALUES (LOWER(REPLACE('J-Ska', ' ', '-')), 'J-Ska');
	INSERT INTO Genre VALUES (LOWER(REPLACE('J-Synth', ' ', '-')), 'J-Synth');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Jackin House', ' ', '-')), 'Jackin House');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Jam Bands', ' ', '-')), 'Jam Bands');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Japan', ' ', '-')), 'Japan');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Japanese Pop', ' ', '-')), 'Japanese Pop');
	INSERT INTO Genre VALUES (LOWER(REPLACE('K-Pop', ' ', '-')), 'K-Pop');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Karaoke', ' ', '-')), 'Karaoke');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Kayokyoku', ' ', '-')), 'Kayokyoku');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Klezmer', ' ', '-')), 'Klezmer');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Latin', ' ', '-')), 'Latin');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Latin Jazz', ' ', '-')), 'Latin Jazz');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Latin Rap', ' ', '-')), 'Latin Rap');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Lo-fi', ' ', '-')), 'Lo-fi');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Lounge', ' ', '-')), 'Lounge');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Love Song', ' ', '-')), 'Love Song');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Lullabies', ' ', '-')), 'Lullabies');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Mainstream Jazz', ' ', '-')), 'Mainstream Jazz');
	INSERT INTO Genre VALUES (LOWER(REPLACE('March', ' ', '-')), 'March');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Math Metal', ' ', '-')), 'Math Metal');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Math Rock', ' ', '-')), 'Math Rock');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Mbalax – Senegal', ' ', '-')), 'Mbalax – Senegal');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Medieval', ' ', '-')), 'Medieval');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Meditation', ' ', '-')), 'Meditation');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Metal', ' ', '-')), 'Metal');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Metal Core', ' ', '-')), 'Metal Core');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Middle East', ' ', '-')), 'Middle East');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Minimalism', ' ', '-')), 'Minimalism');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Modern Composition', ' ', '-')), 'Modern Composition');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Modern Soul', ' ', '-')), 'Modern Soul');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Motown', ' ', '-')), 'Motown');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Movie Soundtrack', ' ', '-')), 'Movie Soundtrack');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Musicals', ' ', '-')), 'Musicals');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Nature', ' ', '-')), 'Nature');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Neo-Soul', ' ', '-')), 'Neo-Soul');
	INSERT INTO Genre VALUES (LOWER(REPLACE('New Acoustic', ' ', '-')), 'New Acoustic');
	INSERT INTO Genre VALUES (LOWER(REPLACE('New Age', ' ', '-')), 'New Age');
	INSERT INTO Genre VALUES (LOWER(REPLACE('New Mex', ' ', '-')), 'New Mex');
	INSERT INTO Genre VALUES (LOWER(REPLACE('New Wave', ' ', '-')), 'New Wave');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Noise Rock', ' ', '-')), 'Noise Rock');
	INSERT INTO Genre VALUES (LOWER(REPLACE('North America', ' ', '-')), 'North America');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Northern Soul', ' ', '-')), 'Northern Soul');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Novelty', ' ', '-')), 'Novelty');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Nuevo Flamenco', ' ', '-')), 'Nuevo Flamenco');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Ode', ' ', '-')), 'Ode');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Old School Rap', ' ', '-')), 'Old School Rap');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Opera', ' ', '-')), 'Opera');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Orchestral', ' ', '-')), 'Orchestral');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Orchestral Pop', ' ', '-')), 'Orchestral Pop');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Original Score', ' ', '-')), 'Original Score');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Outlaw Country', ' ', '-')), 'Outlaw Country');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Piphat – Thailand', ' ', '-')), 'Piphat – Thailand');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Polka', ' ', '-')), 'Polka');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Pop Latino', ' ', '-')), 'Pop Latino');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Pop Punk', ' ', '-')), 'Pop Punk');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Pop Rock', ' ', '-')), 'Pop Rock');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Portuguese fado', ' ', '-')), 'Portuguese fado');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Post Punk', ' ', '-')), 'Post Punk');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Power Pop', ' ', '-')), 'Power Pop');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Praise Worship', ' ', '-')), 'Praise & Worship');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Prog-Rock', ' ', '-')), 'Prog-Rock');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Progressive Metal', ' ', '-')), 'Progressive Metal');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Progressive Rock', ' ', '-')), 'Progressive Rock');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Psychedelic', ' ', '-')), 'Psychedelic');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Psychedelic Soul', ' ', '-')), 'Psychedelic Soul');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Qawwali', ' ', '-')), 'Qawwali');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Quiet Storm', ' ', '-')), 'Quiet Storm');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Ragtime', ' ', '-')), 'Ragtime');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Ragtime Blues', ' ', '-')), 'Ragtime Blues');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Rap', ' ', '-')), 'Rap');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Raices', ' ', '-')), 'Raices');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Reggaeton y Hip-Hop', ' ', '-')), 'Reggaeton y Hip-Hop');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Regional Mexicano', ' ', '-')), 'Regional Mexicano');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Relaxation', ' ', '-')), 'Relaxation');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Renaissance', ' ', '-')), 'Renaissance');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Rock & Roll', ' ', '-')), 'Rock & Roll');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Rockabilly', ' ', '-')), 'Rockabilly');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Romantic', ' ', '-')), 'Romantic');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Roots Reggae', ' ', '-')), 'Roots Reggae');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Roots Rock', ' ', '-')), 'Roots Rock');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Salsa y Tropical', ' ', '-')), 'Salsa y Tropical');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Shoegaze', ' ', '-')), 'Shoegaze');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Sing-Along', ' ', '-')), 'Sing-Along');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Singer Songwriter', ' ', '-')), 'Singer/Songwriter');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Ska', ' ', '-')), 'Ska');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Smooth Jazz', ' ', '-')), 'Smooth Jazz');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Soca', ' ', '-')), 'Soca');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Soft Rock', ' ', '-')), 'Soft Rock');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Soul', ' ', '-')), 'Soul');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Soul Blues', ' ', '-')), 'Soul Blues');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Soundtrack', ' ', '-')), 'Soundtrack');
	INSERT INTO Genre VALUES (LOWER(REPLACE('South Africa', ' ', '-')), 'South Africa');
	INSERT INTO Genre VALUES (LOWER(REPLACE('South America', ' ', '-')), 'South America');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Southern Gospel', ' ', '-')), 'Southern Gospel');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Southern Rock', ' ', '-')), 'Southern Rock');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Southern Soul', ' ', '-')), 'Southern Soul');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Spazzcore', ' ', '-')), 'Spazzcore');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Spoken Word', ' ', '-')), 'Spoken Word');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Standards', ' ', '-')), 'Standards');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Standup Comedy', ' ', '-')), 'Standup Comedy');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Steampunk', ' ', '-')), 'Steampunk');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Stoner Metal', ' ', '-')), 'Stoner Metal');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Stories', ' ', '-')), 'Stories');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Surf', ' ', '-')), 'Surf');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Swing', ' ', '-')), 'Swing');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Synthpop', ' ', '-')), 'Synthpop');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Technical Death Metal', ' ', '-')), 'Technical Death Metal');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Techno', ' ', '-')), 'Techno');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Teen Pop', ' ', '-')), 'Teen Pop');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Tex-Mex', ' ', '-')), 'Tex-Mex');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Time Lord Rock', ' ', '-')), 'Time Lord Rock');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Traditional Bluegrass', ' ', '-')), 'Traditional Bluegrass');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Traditional Celtic', ' ', '-')), 'Traditional Celtic');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Traditional Country', ' ', '-')), 'Traditional Country');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Traditional Folk', ' ', '-')), 'Traditional Folk');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Traditional Gospel', ' ', '-')), 'Traditional Gospel');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Traditional Pop', ' ', '-')), 'Traditional Pop');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Trad Jazz', ' ', '-')), 'Trad Jazz');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Trance', ' ', '-')), 'Trance');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Trap', ' ', '-')), 'Trap');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Trash Metal', ' ', '-')), 'Trash Metal');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Travel', ' ', '-')), 'Travel');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Trip Hop', ' ', '-')), 'Trip Hop');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Turntablism', ' ', '-')), 'Turntablism');
	INSERT INTO Genre VALUES (LOWER(REPLACE('TV Soundtrack', ' ', '-')), 'TV Soundtrack');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Underground Rap', ' ', '-')), 'Underground Rap');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Urban Cowboy', ' ', '-')), 'Urban Cowboy');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Vaudeville', ' ', '-')), 'Vaudeville');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Vocal', ' ', '-')), 'Vocal');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Vocal Jazz', ' ', '-')), 'Vocal Jazz');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Vocal Pop', ' ', '-')), 'Vocal Pop');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Wedding Music', ' ', '-')), 'Wedding Music');
	INSERT INTO Genre VALUES (LOWER(REPLACE('West Coast Rap', ' ', '-')), 'West Coast Rap');
	INSERT INTO Genre VALUES (LOWER(REPLACE('World', ' ', '-')), 'World');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Worldbeat', ' ', '-')), 'Worldbeat');
	INSERT INTO Genre VALUES (LOWER(REPLACE('Zydeco', ' ', '-')), 'Zydeco');
END