CREATE PROCEDURE [dbo].[DeleteAndSeedGenres]
AS
BEGIN
	DELETE FROM [Genre];

	DBCC CHECKIDENT ('[Genre]', RESEED, 0);

	INSERT INTO Genre VALUES ('acoustic', 'Acoustic');
	INSERT INTO Genre VALUES ('afrobeat', 'Afrobeat');
	INSERT INTO Genre VALUES ('alt-rock', 'Alt Rock');
	INSERT INTO Genre VALUES ('alternative', 'Alternative');
	INSERT INTO Genre VALUES ('ambient', 'Ambient');
	INSERT INTO Genre VALUES ('anime', 'Anime');
	INSERT INTO Genre VALUES ('black-metal', 'Black Metal');
	INSERT INTO Genre VALUES ('bluegrass', 'Bluegrass');
	INSERT INTO Genre VALUES ('blues', 'Blues');
	INSERT INTO Genre VALUES ('bossanova', 'Bossanova');
	INSERT INTO Genre VALUES ('brazil', 'Brazil');
	INSERT INTO Genre VALUES ('breakbeat', 'Breakbeat');
	INSERT INTO Genre VALUES ('british', 'British');
	INSERT INTO Genre VALUES ('cantopop', 'Cantopop');
	INSERT INTO Genre VALUES ('chicago-house', 'Chicago House');
	INSERT INTO Genre VALUES ('children', 'Children');
	INSERT INTO Genre VALUES ('chill', 'Chill');
	INSERT INTO Genre VALUES ('classical', 'Classical');
	INSERT INTO Genre VALUES ('club', 'Club');
	INSERT INTO Genre VALUES ('comedy', 'Comedy');
	INSERT INTO Genre VALUES ('country', 'Country');
	INSERT INTO Genre VALUES ('dance', 'Dance');
	INSERT INTO Genre VALUES ('dancehall', 'Dancehall');
	INSERT INTO Genre VALUES ('death-metal', 'Death Metal');
	INSERT INTO Genre VALUES ('deep-house', 'Deep House');
	INSERT INTO Genre VALUES ('detroit-techno', 'Detroit Techno');
	INSERT INTO Genre VALUES ('disco', 'Disco');
	INSERT INTO Genre VALUES ('disney', 'Disney');
	INSERT INTO Genre VALUES ('drum-and-bass', 'Drum & Bass');
	INSERT INTO Genre VALUES ('dub', 'Dub');
	INSERT INTO Genre VALUES ('dubstep', 'Dubstep');
	INSERT INTO Genre VALUES ('edm', 'Edm');
	INSERT INTO Genre VALUES ('electro', 'Electro');
	INSERT INTO Genre VALUES ('electronic', 'Electronic');
	INSERT INTO Genre VALUES ('emo', 'Emo');
	INSERT INTO Genre VALUES ('folk', 'Folk');
	INSERT INTO Genre VALUES ('forro', 'Forro');
	INSERT INTO Genre VALUES ('french', 'French');
	INSERT INTO Genre VALUES ('funk', 'Funk');
	INSERT INTO Genre VALUES ('garage', 'Garage');
	INSERT INTO Genre VALUES ('german', 'German');
	INSERT INTO Genre VALUES ('gospel', 'Gospel');
	INSERT INTO Genre VALUES ('goth', 'Goth');
	INSERT INTO Genre VALUES ('grindcore', 'Grindcore');
	INSERT INTO Genre VALUES ('groove', 'Groove');
	INSERT INTO Genre VALUES ('grunge', 'Grunge');
	INSERT INTO Genre VALUES ('guitar', 'Guitar');
	INSERT INTO Genre VALUES ('happy', 'Happy');
	INSERT INTO Genre VALUES ('hard-rock', 'Hard Rock');
	INSERT INTO Genre VALUES ('hardcore', 'Hardcore');
	INSERT INTO Genre VALUES ('hardstyle', 'Hardstyle');
	INSERT INTO Genre VALUES ('heavy-metal', 'Heavy Metal');
	INSERT INTO Genre VALUES ('hip-hop', 'Hip Hop');
	INSERT INTO Genre VALUES ('holidays', 'Holidays');
	INSERT INTO Genre VALUES ('honky-tonk', 'Honky Tonk');
	INSERT INTO Genre VALUES ('house', 'House');
	INSERT INTO Genre VALUES ('idm', 'Idm');
	INSERT INTO Genre VALUES ('indian', 'Indian');
	INSERT INTO Genre VALUES ('indie', 'Indie');
	INSERT INTO Genre VALUES ('indie-pop', 'Indie Pop');
	INSERT INTO Genre VALUES ('industrial', 'Industrial');
	INSERT INTO Genre VALUES ('iranian', 'Iranian');
	INSERT INTO Genre VALUES ('j-dance', 'J-Dance');
	INSERT INTO Genre VALUES ('j-idol', 'J-Idol');
	INSERT INTO Genre VALUES ('j-pop', 'J-Pop');
	INSERT INTO Genre VALUES ('j-rock', 'J-Rock');
	INSERT INTO Genre VALUES ('jazz', 'Jazz');
	INSERT INTO Genre VALUES ('k-pop', 'K Pop');
	INSERT INTO Genre VALUES ('kids', 'Kids');
	INSERT INTO Genre VALUES ('latin', 'Latin');
	INSERT INTO Genre VALUES ('latino', 'Latino');
	INSERT INTO Genre VALUES ('malay', 'Malay');
	INSERT INTO Genre VALUES ('mandopop', 'Mandopop');
	INSERT INTO Genre VALUES ('metal', 'Metal');
	INSERT INTO Genre VALUES ('metal-misc', 'Metal Misc');
	INSERT INTO Genre VALUES ('metalcore', 'Metalcore');
	INSERT INTO Genre VALUES ('minimal-techno', 'Minimal Techno');
	INSERT INTO Genre VALUES ('movies', 'Movies');
	INSERT INTO Genre VALUES ('mpb', 'Mpb');
	INSERT INTO Genre VALUES ('new-age', 'New Age');
	INSERT INTO Genre VALUES ('new-release', 'New Release');
	INSERT INTO Genre VALUES ('opera', 'Opera');
	INSERT INTO Genre VALUES ('pagode', 'Pagode');
	INSERT INTO Genre VALUES ('party', 'Party');
	INSERT INTO Genre VALUES ('philippines-opm', 'Philippines Opm');
	INSERT INTO Genre VALUES ('piano', 'Piano');
	INSERT INTO Genre VALUES ('pop', 'Pop');
	INSERT INTO Genre VALUES ('pop-film', 'Pop Film');
	INSERT INTO Genre VALUES ('post-dubstep', 'Post Dubstep');
	INSERT INTO Genre VALUES ('power-pop', 'Power Pop');
	INSERT INTO Genre VALUES ('progressive-house', 'Progressive House');
	INSERT INTO Genre VALUES ('psych-rock', 'Psych Rock');
	INSERT INTO Genre VALUES ('punk', 'Punk');
	INSERT INTO Genre VALUES ('punk-rock', 'Punk Rock');
	INSERT INTO Genre VALUES ('r-n-b', 'R&B');
	INSERT INTO Genre VALUES ('rainy-day', 'Rainy Day');
	INSERT INTO Genre VALUES ('reggae', 'Reggae');
	INSERT INTO Genre VALUES ('reggaeton', 'Reggaeton');
	INSERT INTO Genre VALUES ('road-trip', 'Road Trip');
	INSERT INTO Genre VALUES ('rock', 'Rock');
	INSERT INTO Genre VALUES ('rock-n-roll', 'Rock n Roll');
	INSERT INTO Genre VALUES ('rockabilly', 'Rockabilly');
	INSERT INTO Genre VALUES ('romance', 'Romance');
	INSERT INTO Genre VALUES ('sad', 'Sad');
	INSERT INTO Genre VALUES ('salsa', 'Salsa');
	INSERT INTO Genre VALUES ('samba', 'Samba');
	INSERT INTO Genre VALUES ('sertanejo', 'Sertanejo');
	INSERT INTO Genre VALUES ('show-tunes', 'Show Tunes');
	INSERT INTO Genre VALUES ('singer-songwriter', 'Singer Songwriter');
	INSERT INTO Genre VALUES ('ska', 'Ska');
	INSERT INTO Genre VALUES ('sleep', 'Sleep');
	INSERT INTO Genre VALUES ('songwriter', 'Songwriter');
	INSERT INTO Genre VALUES ('soul', 'Soul');
	INSERT INTO Genre VALUES ('soundtracks', 'Soundtracks');
	INSERT INTO Genre VALUES ('spanish', 'Spanish');
	INSERT INTO Genre VALUES ('study', 'Study');
	INSERT INTO Genre VALUES ('summer', 'Summer');
	INSERT INTO Genre VALUES ('swedish', 'Swedish');
	INSERT INTO Genre VALUES ('synth-pop', 'Synth Pop');
	INSERT INTO Genre VALUES ('tango', 'Tango');
	INSERT INTO Genre VALUES ('techno', 'Techno');
	INSERT INTO Genre VALUES ('trance', 'Trance');
	INSERT INTO Genre VALUES ('trip-hop', 'Trip Hop');
	INSERT INTO Genre VALUES ('turkish', 'Turkish');
	INSERT INTO Genre VALUES ('work-out', 'Work Out');
	INSERT INTO Genre VALUES ('world-music', 'World Music');
END